### ISSUE TITLE
Could not map protobuf in proto sink mapper throwing error IllegalArgumentException

### ISSUE THREAD

**Issue by fritzwijaya** [siddhi-io/siddhi-map-protobuf#21]
**Description:**
Error: java.lang.IllegalArgumentException: object is not an instance of declaring class
Is throwed when mapping siddhi event using proto sink mapper. The Java generated proto class

Full stack trace:
`java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.siddhi.extension.map.protobuf.sinkmapper.ProtobufSinkMapper.mapAndSend(ProtobufSinkMapper.java:299)
	at io.siddhi.core.stream.output.sink.SinkMapper.mapAndSend(SinkMapper.java:180)
	at io.siddhi.core.stream.output.sink.SinkCallback.receive(SinkCallback.java:55)
	at io.siddhi.core.stream.output.StreamCallback.receive(StreamCallback.java:100)
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:179)
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:496)
	at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)
	at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104)
	at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:44)
	at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:97)
	at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:182)
	at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:89)
	at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:127)
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:202)
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:505)
	at io.siddhi.core.stream.input.InputDistributor.send(InputDistributor.java:34)
	at io.siddhi.core.stream.input.InputEntryValve.send(InputEntryValve.java:45)
	at io.siddhi.core.stream.input.InputHandler.send(InputHandler.java:78)
	at io.siddhi.core.stream.input.source.PassThroughSourceHandler.sendEvent(PassThroughSourceHandler.java:35)
	at io.siddhi.core.stream.input.source.InputEventHandler.sendEvent(InputEventHandler.java:82)
	at io.siddhi.extension.map.json.sourcemapper.JsonSourceMapper.mapAndProcess(JsonSourceMapper.java:255)
	at io.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:200)
	at io.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:144)
	at io.siddhi.extension.io.http.source.HttpSyncWorkerThread.run(HttpSyncWorkerThread.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Affected Product Version:**
siddhi-map-protobuf v1.1.0

**Steps to reproduce:**
Running the sample on docs.
https://siddhi-io.github.io/siddhi-map-protobuf/api/1.1.0/#protobuf-source-mapper

**Comment by fritzwijaya** [comment]
False alarm. Issue on siddhi-io-kafka component
